services:
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis-data:/data
    command: redis-server
    restart: unless-stopped
    networks:
      - redis-network

  septum:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Septum
    restart: unless-stopped
    ports:
      - "4000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge

volumes:
  redis-data:
